import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>FingerPrint reader JAVA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            There is no specific code for a fingerprint reader in Java, as the process of reading fingerprints typically involves using a device driver to communicate with the fingerprint reader hardware, and this device driver is specific to the device being used. However, here is an example of how you can use the Java Fingerprint SDK to capture and verify fingerprints.

import com.digitalpersona.onetouch.*;
import com.digitalpersona.onetouch.verification.*;

public class VerifyFingerprint
{
    public static void main(String[] args)
    {
        DPFPVerification verificator = DPFPGlobal.getVerificationFactory().createVerification();

        while (true)
        {
            // Prompt the user to enter their fingerprint
            DPFPFingerIndex finger = DPFPConsole.getFingerIndex();
            if (finger == DPFPFingerIndex.LEFT_THUMB || finger == DPFPFingerIndex.RIGHT_THUMB)
                break;

            // Capture their fingerprint
            DPFPSample sample = DPFPConsole.getSample(
                String.format("Scan your %s finger", finger),
                DPFPSample.PURPOSE_VERIFICATION
            );

            // Verify the fingerprint against the enrolled fingerprint
            DPFPVerificationResult result = verificator.verify(sample, enrolledSample);
            if (result.isVerified())
                System.out.println("Fingerprint verified!");
            else
                System.out.println("Fingerprint not recognized, try again.");
        }
    }
}
<p>Code by <a href="https://gharvisit.com">Gharvisit</a> and <a href="https://allalerts.in">All alerts</a></p>
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
